name: Daily YouTube Trend Report

on:
  schedule:
    # 매일 KST 08:00 → UTC 23:00
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas openai openpyxl

      - name: Run trend script
        run: python youtube_trend_channel_generator.py
        env:
          YT_API_KEY:     ${{ secrets.YT_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
